name: macros_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  dio: ^5.3.2

  pie_chart: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  test: ^1.24.1
#flutter pub run build_runner watch

flutter:
  uses-material-design: true

  fonts:
    - family: rawline
      fonts:
        - asset: assets\fonts\rawline-500.ttf
